### ISSUE TITLE
Crash on monitoring

### ISSUE THREAD

**Issue by abalta** [Omico/CurrentActivity#9]
I have built your project. Shizuku is ready and all permission allowed. When I toggle enable monitor switch on. App has crashed.

LogCat:

```
FATAL EXCEPTION: main
                                                                                                    Process: me.omico.currentactivity.debug, PID: 17388
                                                                                                    java.lang.NoSuchMethodError: No interface method getTasks(I)Ljava/util/List; in class Landroid/app/IActivityTaskManager; or its super classes (declaration of 'android.app.IActivityTaskManager' appears in /system/framework/framework.jar)
                                                                                                    	at me.omico.currentactivity.shizuku.ShizukuSystemServiceApiKt.getTopActivity(ShizukuSystemServiceApi.kt:27)
                                                                                                    	at me.omico.currentactivity.ui.ShizukuKt$rememberCurrentActivityText$1.invokeSuspend(Shizuku.kt:104)
                                                                                                    	at me.omico.currentactivity.ui.ShizukuKt$rememberCurrentActivityText$1.invoke(Unknown Source:8)
                                                                                                    	at me.omico.currentactivity.ui.ShizukuKt$rememberCurrentActivityText$1.invoke(Unknown Source:4)
                                                                                                    	at androidx.compose.runtime.SnapshotStateKt__ProduceStateKt$produceState$1.invokeSuspend(ProduceState.kt:86)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:57)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7918)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                                                                    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@b8fbe2b, androidx.compose.runtime.BroadcastFrameClock@8674288, StandaloneCoroutine{Cancelling}@76cf421, AndroidUiDispatcher@e4c3046]
```

**Comment by abalta** [comment]
I think I solve the issue. getTasks method takes more parameters. Like this: 
```
val topActivity: ComponentName?
    get() = activityTaskManager.getTasks(1, false, false, 0).first().topActivity
```

Here is for the reference: `https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/app/IActivityTaskManager.aidl;l=95?q=IActivityTaskManager`

**Comment by Omico** [comment]
Thanks! This should be fixed in https://github.com/Omico/CurrentActivity/commit/a0a512eb5cb4a4e1a23a7173470ac1e22edf8fee

**Comment by abalta** [comment]
Now, it has not crashed, but this time current activity title not changes. It always shows
```
me.omico.currentactivity.debug
me.omico.currentactivity.ui.main.MainActivity
```

**Comment by Omico** [comment]
@abalta A huge thanks! I just remembered that we need to get a system instance of IActivityTaskManager. For more info, please look at the comments in this commit. https://github.com/Omico/CurrentActivity/commit/5631de64c129fc5c6f2448499f946ec22c28d763
